import { ResolverXML } from "../core/types/resolver";

export const GitResolver:ResolverXML<['pull','create']> = {
  pull:{
    name:'pull',
    query:{
      packet:{
        extension:{
          call:{
            git:{
              fetch:{
                domain:'{domain}',
                name:'{repo}'
              },
              deploy:{
                domain:'{domain}',
                name:'{repo}'
              }
            }
          }
        }
      }
    }
  },
  create:{
    name:'create',
    query:{
      packet:{
        extension:{
          call:{
            git:{
              create:{
                domain:'{domain}',
                name:'{repo}',
                "remote-url":'{remoteUrl}',
                "deployment-path":'httpdocs',
                "depolyment-mode":'auto'
              }
            }
          }
        }
      }
    }
  }
}